# Generated by Django 5.1.4 on 2024-12-30 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filedigitization', '0003_backup_reportrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogs',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filedigitization.document'),
        ),
    ]
