# Generated by Django 5.1.4 on 2024-12-31 06:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filedigitization', '0004_alter_auditlogs_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='accessible_users',
            field=models.ManyToManyField(related_name='document_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
