# Generated by Django 5.1.4 on 2025-01-12 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filedigitization', '0006_accessrequest_approval_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='document',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_file',
            field=models.FileField(blank=True, null=True, upload_to='notifications/'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='NotificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=150, unique=True)),
                ('device_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'token')},
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='filedigitization.notificationtoken'),
        ),
        migrations.DeleteModel(
            name='AccessRequest',
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
    ]
